(function(root){
const D=()=>root.VerbHeistData,C=()=>root.VerbHeistCore;
let host,state,sound=true,closeFn;
function start(el,onClose){host=el;closeFn=onClose;state=C().createState(D());render()}
function verb(){return state.verbs[state.block]}
function task(){const v=verb(),variant=(state.block+state.taskVariant)%2;if(state.task===0){const t=v.recallTasks[variant];return{type:'recall',sentence:t.sentence,target:t.target,answer:t.target==='past'?v.past:v.participle}}if(state.task===1){const t=v.recallTasks[(variant+1)%2];return{type:'tense-choice',sentence:t.sentence,target:t.target,answer:t.target==='past'?v.past:v.participle}}const t=v.repairTasks[variant];return{type:'repair',sentence:t.sentence,target:t.correctForm===v.past?'past':'participle',answer:t.correctForm,wrong:t.wrongForm}}
function render(){if(state.status==='completed')return renderResults();if(state.status==='failed')return renderAlert();const t=task(),progress=(state.block*3+state.task)/15*100;host.innerHTML=`<div class="heist" id="heist"><header class="heist-header"><div><span>THE VERB HEIST</span><b>CASE 014</b></div><div class="heist-stats"><span>SCORE <b>${state.score}</b></span><span>STREAK <b>${state.streak}</b></span><span class="lives" aria-label="${state.lives} жизни">${[0,1,2].map(i=>`<i class="${i<state.lives?'on':''}"></i>`).join('')}</span><button id="soundToggle" aria-label="Звук">${sound?'SOUND ON':'SOUND OFF'}</button></div></header><div class="heist-progress"><i style="width:${progress}%"></i></div><main class="heist-layout"><section class="safe-side">${safeHtml()}</section><section class="task-panel"><div class="task-number">TASK ${state.block*3+state.task+1} / 15 · ${['RECALL','V2 OR V3','REPAIR'][state.task]}</div><h2>${taskSentence(t)}</h2><div class="verb-label">VERB <strong>${verb().base.toUpperCase()}</strong></div>${t.type==='tense-choice'?`<div class="tense-switch"><button data-tense="past">V2 <small>Past Simple</small></button><button data-tense="participle">V3 <small>Past Participle</small></button></div>`:''}<form id="answerForm"><label for="verbAnswer">${t.type==='repair'?'Исправьте выделенное слово':'Введите нужную форму'}</label><div class="answer-row"><input id="verbAnswer" autocomplete="off" autocapitalize="none" spellcheck="false"><button>CONFIRM</button></div></form><div class="task-actions"><button id="hintBtn">HINT <span>−25</span></button></div><p class="heist-feedback" id="heistFeedback" aria-live="polite"></p></section></main></div>`;bind()}
function safeHtml(){return `<div class="safe-title">ARCHIVE VAULT <span>${state.opened}/5</span></div><div class="safe-shell ${state.status==='sectionOpening'?'opening':''}"><div class="safe-lamp"></div><div class="safe-lock"><i></i></div><div class="safe-grid">${[0,1,2,3,4].map(i=>`<div class="safe-cell ${i<state.opened?'open':''}" style="--piece:${i}"><div class="safe-door"><span>0${i+1}</span></div><div class="document-piece"></div></div>`).join('')}</div></div><p class="safe-caption">Каждые три ответа открывают одну секцию</p>`}
function taskSentence(t){if(t.type!=='repair')return t.sentence.replace('___','<mark>___</mark>');const escaped=t.sentence.replace(t.wrong,`<mark>${t.wrong}</mark>`);return escaped}
function bind(){document.querySelector('#soundToggle').onclick=()=>{sound=!sound;render()};const form=document.querySelector('#answerForm'),input=document.querySelector('#verbAnswer');form.onsubmit=e=>{e.preventDefault();submit(input.value)};document.querySelector('#hintBtn').onclick=hint;document.querySelectorAll('[data-tense]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tense]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selectedTense=b.dataset.tense;tone(260,.035)});setTimeout(()=>input.focus(),30)}
function submit(value){const t=task(),feedback=document.querySelector('#heistFeedback');if(!C().normalize(value)){shake();feedback.textContent='Введите форму глагола.';return}if(t.type==='tense-choice'&&!state.selectedTense){feedback.textContent='Сначала выберите V2 или V3.';return}state.attempt++;state.answered++;let tenseOK=true;if(t.type==='tense-choice'){tenseOK=state.selectedTense===t.target;if(!tenseOK){feedback.textContent=t.target==='participle'?'CHECK THE TENSE - has + ...':'CHECK THE TENSE - finished time';document.querySelector(`[data-tense="${state.selectedTense}"]`).classList.add('wrong');state.errors++;state.blockErrors++;state.streak=0;errorSound();return}}
 if(C().checkAnswer(value,t.answer)){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);state.score+=C().scoreFor(state.attempt,false,state.streak);feedback.className='heist-feedback correct';feedback.textContent=`CORRECT - ${t.answer.toUpperCase()}`;correctSound();setTimeout(nextTask,700)}else{state.errors++;state.blockErrors++;state.streak=0;shake();errorSound();if(state.attempt<2){feedback.textContent=`NOT QUITE - ${t.target==='past'?'Past Simple':'Past Participle'} of ${verb().base}`;document.querySelector('#verbAnswer').select()}else{state.lives=Math.max(0,state.lives-1);feedback.textContent=`${verb().base.toUpperCase()} - ${verb().past.toUpperCase()} - ${verb().participle.toUpperCase()}`;setTimeout(()=>state.lives<=0&&!state.practice?securityAlert():nextTask(),850)}}}
function hint(){const feedback=document.querySelector('#heistFeedback'),button=document.querySelector('#hintBtn');if(state.hintUsed){state.hintVisible=!state.hintVisible;feedback.textContent=state.hintVisible?state.hintText:'';button.classList.toggle('used',state.hintVisible);button.setAttribute('aria-pressed',state.hintVisible);return}state.hintUsed=true;state.hintVisible=true;state.score=Math.max(0,state.score-25);const t=task(),tips=[`Starts with ${t.answer[0].toUpperCase()}`,`${t.answer.length} letters`,t.target==='past'?'Finished time → use V2':'Perfect/passive → use V3'];state.hintText=tips[(state.block+state.task)%tips.length];feedback.textContent=state.hintText;button.classList.add('used');button.setAttribute('aria-pressed','true');document.querySelector('.heist-stats span:first-child b').textContent=state.score;tone(330,.06)}
function nextTask(){state.attempt=0;state.hintUsed=false;state.hintVisible=false;state.hintText='';state.selectedTense=null;if(state.task<2){state.task++;render()}else{if(state.blockErrors===0)state.score+=150;state.status='sectionOpening';state.opened++;render();openSound();setTimeout(()=>{if(state.opened===5){state.status='completed';saveBest();render()}else{state.block++;state.task=0;state.blockErrors=0;state.status='playing';render()}},850)}}
function securityAlert(){state.status='failed';render();errorSound()}
function renderAlert(){host.innerHTML=`<div class="heist alert-screen"><span>ARCHIVE SECURITY</span><h2>SECURITY ALERT</h2><p>Все жизни потрачены. Можно начать операцию заново или продолжить тренировку без сохранения рекорда.</p><div><button id="restartHeist">НАЧАТЬ ЗАНОВО</button><button id="continueHeist">ПРОДОЛЖИТЬ</button></div></div>`;document.querySelector('#restartHeist').onclick=()=>start(host,closeFn);document.querySelector('#continueHeist').onclick=()=>{state.practice=true;state.noRecord=true;state.status='playing';render()}}
function saveBest(){if(state.noRecord)return;const best=+(localStorage.getItem('verbHeistBest')||0);if(state.score>best)localStorage.setItem('verbHeistBest',state.score)}
function renderResults(){const accuracy=Math.round(state.correct/Math.max(1,state.answered)*100),best=Math.max(state.score,+(localStorage.getItem('verbHeistBest')||0));host.innerHTML=`<div class="heist results"><div class="final-document"><span>SECRET ARCHIVE</span><b>CASE<br>CLOSED</b><small>ACCESS GRANTED · 014</small></div><p class="result-kicker">ALL FIVE SECTIONS OPEN</p><h2>CASE CLOSED</h2><div class="result-stats"><span>Score <b>${state.score}</b></span><span>Accuracy <b>${accuracy}%</b></span><span>Best streak <b>${state.bestStreak}</b></span><span>Errors <b>${state.errors}</b></span></div><p>Verbs practised: <strong>${state.verbs.map(v=>v.base).join(', ')}</strong></p><small>Best score: ${best}</small><div class="result-actions"><button id="playAgain">СЫГРАТЬ ЕЩЁ РАЗ</button><button id="backCases">ВЕРНУТЬСЯ К ДЕЛАМ</button></div></div>`;finalSound();document.querySelector('#playAgain').onclick=()=>start(host,closeFn);document.querySelector('#backCases').onclick=closeFn}
function shake(){const x=document.querySelector('#verbAnswer');x.classList.remove('wrong');void x.offsetWidth;x.classList.add('wrong')}
function tone(f,d,type='sine',delay=0){if(!sound)return;try{const A=root.AudioContext||root.webkitAudioContext,c=tone.ctx||(tone.ctx=new A),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.06,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+delay+d);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d)}catch(e){}}
function correctSound(){tone(420,.08);tone(660,.18,'sine',.08)}function errorSound(){tone(110,.16,'sawtooth')}function openSound(){tone(90,.09,'square');tone(250,.12,'triangle',.1);tone(520,.25,'sine',.2)}function finalSound(){[330,440,550,720].forEach((f,i)=>tone(f,.3,'sine',i*.1))}
root.VerbHeist={start};
})(window);
