(function(){
 const D=()=>window.SignalInterceptData,C=()=>window.SignalInterceptCore;let root,onClose,state,audio,pauseTimer,pauseResume,noiseContext,noiseSource;
 const esc=s=>{const x=document.createElement('span');x.textContent=s;return x.innerHTML};
 const reverse=s=>Array.from(s).reverse().join('');
 function fresh(){return{index:0,score:0,attempts:0,hints:0,hintVisible:false,listens:0,status:'intro',input:'',progress:[],messages:Array.from({length:5},()=>({input:'',attempts:0,hints:0,hintVisible:false,done:false,accuracy:0})),sound:localStorage.getItem('signalUiSound')!=='off',playing:false,position:0,mode:null}}
 function start(el,close){root=el;onClose=close;state=fresh();render()}
 function stop(){clearTimeout(pauseTimer);pauseResume=null;if(audio){audio.pause();audio=null}stopNoise()}
 function tone(freq=500,d=.06){if(!state.sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g).connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch(e){}}
 function header(){return `<header class="signal-header"><div><b>SIGNAL INTERCEPT</b><small>ДЕЛО №021</small></div><span>СООБЩЕНИЕ ${state.index+1} / 5</span><div class="signal-stats"><span>SCORE <b>${state.score}</b></span><button data-action="sound" aria-label="Звуки интерфейса">${state.sound?'◉ ЗВУК':'○ БЕЗ ЗВУКА'}</button></div></header>`}
 function render(){stop();root.innerHTML=`<div class="signal-game">${state.status==='intro'?intro():state.status==='results'?results():header()+playScreen()}</div>`;bind();if(state.status==='playing')setTimeout(()=>root.querySelector('textarea')?.focus(),30)}
 function intro(){return `<section class="signal-intro"><div class="radar">⌁<i></i></div><p>СЕКРЕТНЫЙ КЛУБ · ПЕРЕХВАЧЕННЫЙ КАНАЛ</p><h2>SIGNAL<br>INTERCEPT</h2><b>Тренируем: аудирование и правописание</b><span>Прослушай пять сообщений и восстанови их точный английский текст.</span><button data-action="begin">ПРИНЯТЬ СИГНАЛ →</button></section>`}
 function playScreen(){const m=D()[state.index];return `<main class="signal-simple"><section class="receiver"><div class="receiver-label"><span>CHANNEL 0${state.index+1} · B1</span><b>${state.playing?'RECEIVING':'SIGNAL READY'}</b></div><div class="radio-scale"><span>88</span><span>92</span><span>96</span><b>SECURE BAND</b><span>104</span><span>108</span><i></i></div><div class="wave-navigation"><button data-action="prev-message" aria-label="Предыдущее сообщение">‹</button><div class="wave ${state.playing?'active':''}" style="--pos:${state.position/m.duration*100}%">${Array.from({length:54},(_,i)=>`<i style="height:${18+(i*17%55)}%"></i>`).join('')}<em></em></div><button data-action="next-message" aria-label="Следующее сообщение">›</button></div><div class="transport"><span>${fmt(state.position)} / ${fmt(m.duration)}</span></div><div class="listen-modes"><button data-mode="normal" class="${state.mode==='normal'?'active':''}"><i>▶</i><span>ОБЫЧНОЕ ПРОСЛУШИВАНИЕ<small>Естественный темп</small></span></button><button data-mode="slow" class="${state.mode==='slow'?'active':''}"><i>◷</i><span>ЗАМЕДЛЕННОЕ<small>Вся запись · скорость 0.75</small></span></button><button data-mode="pauses" class="${state.mode==='pauses'?'active':''}"><i>Ⅱ</i><span>С ПАУЗАМИ<small>Короткая пауза между фразами</small></span></button></div></section><section class="console simple-console"><div class="transcript"><div><b>РАСШИФРОВКА</b><span>${words(state.input)} слов</span></div><textarea rows="5" maxlength="180" placeholder="Введи услышанное сообщение на английском">${esc(state.input)}</textarea><div class="transcript-actions"><button data-action="clear">ОЧИСТИТЬ</button><button data-action="hint" class="${state.hintVisible?'active':''}" aria-pressed="${state.hintVisible}">ПОДСКАЗКА</button><button class="decode" data-action="check">ПРОВЕРИТЬ РАСШИФРОВКУ</button></div><div class="hint-box ${state.hintVisible?'visible':''}">${state.hintVisible?`<b>ЭХО С ТОЙ СТОРОНЫ КАНАЛА</b><p>${esc(reverse(m.transcript))}</p>`:''}</div><div class="feedback" aria-live="polite"></div></div></section></main>`}
 function fmt(v){return `00:${String(Math.floor(v)).padStart(2,'0')}`}function words(v){return C().normalize(v).split(' ').filter(Boolean).length}
 function bind(){root.onclick=click;const ta=root.querySelector('textarea');if(ta){ta.readOnly=state.messages[state.index].done;ta.oninput=e=>{state.input=e.target.value;state.messages[state.index].input=state.input};ta.onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||!e.shiftKey)){e.preventDefault();check()}}}}
 function click(e){const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='begin'){state.status='playing';tone(700,.12);render()}else if(a==='sound'){toggleSound(b)}else if(b.dataset.mode)playMode(b.dataset.mode);else if(b.dataset.phrase!==undefined)playPhrase(+b.dataset.phrase);else if(a==='prev-message')switchMessage(-1);else if(a==='next-message')switchMessage(1);else if(a==='clear'){if(state.messages[state.index].done)return;state.input='';state.messages[state.index].input='';render()}else if(a==='hint'){if(state.messages[state.index].done)return;state.hintVisible=!state.hintVisible;state.messages[state.index].hintVisible=state.hintVisible;if(state.hintVisible){state.hints=1;state.messages[state.index].hints=1}render()}else if(a==='check')check();else if(a==='reveal'){state.input=D()[state.index].transcript;state.messages[state.index].input=state.input;render()}else if(a==='next')next();else if(a==='restart'){state=fresh();render()}else if(a==='close')onClose();else if(b.dataset.option!==undefined)answer(+b.dataset.option)}
 function toggleSound(button){state.sound=!state.sound;localStorage.setItem('signalUiSound',state.sound?'on':'off');if(audio)audio.muted=!state.sound;if(state.sound&&audio&&!audio.paused)startNoise();else stopNoise();button.textContent=state.sound?'◉ ЗВУК':'○ БЕЗ ЗВУКА'}
 function setPlayingUi(){root.querySelector('.wave')?.classList.toggle('active',state.playing);const label=root.querySelector('.receiver-label b');if(label)label.textContent=state.playing?'RECEIVING':'SIGNAL READY'}
 function pauseCurrent(){clearTimeout(pauseTimer);audio?.pause();stopNoise();state.playing=false;setPlayingUi()}
 function resumeCurrent(){if(!audio)return false;state.playing=true;setPlayingUi();if(pauseResume){const resume=pauseResume;pauseResume=null;resume()}else{startNoise();audio.play().catch(audioError)}return true}
 function playMode(mode){if(state.mode===mode&&audio){if(state.playing)pauseCurrent();else resumeCurrent();return}state.mode=mode;if(mode==='pauses')playWithPauses();else playAudio(0,D()[state.index].duration,mode==='slow'?.75:1)}
 function saveCurrent(){const m=state.messages[state.index];m.input=state.input;m.attempts=state.attempts;m.hints=state.hints;m.hintVisible=state.hintVisible;m.accuracy=state.lastAccuracy||m.accuracy}
 function switchMessage(stepOrIndex,direct=false){saveCurrent();stop();state.index=direct?stepOrIndex:(state.index+stepOrIndex+5)%5;const m=state.messages[state.index];state.input=m.input;state.attempts=m.attempts;state.hints=m.hints;state.hintVisible=m.hintVisible;state.lastAccuracy=m.accuracy;state.position=0;state.playing=false;state.mode=null;state.status='playing';render()}
 function playPhrase(i){const p=D()[state.index].phrases[i];playAudio(p.start,p.end,1)}
 function playWithPauses(){stop();const m=D()[state.index],boundaries=m.phrases.slice(0,-1).map(p=>p.end);let boundary=0,waiting=false;state.listens++;state.playing=true;state.position=0;updatePlayer();audio=new Audio(m.audioSrc);audio.muted=!state.sound;audio.preload='auto';audio.playbackRate=1;audio.addEventListener('canplay',()=>{startNoise();audio.play().catch(audioError)},{once:true});audio.addEventListener('timeupdate',()=>{if(!audio)return;state.position=audio.currentTime;updatePlayer();if(!waiting&&boundary<boundaries.length&&audio.currentTime>=boundaries[boundary]){waiting=true;audio.pause();stopNoise();boundary++;pauseResume=()=>{if(!audio)return;waiting=false;startNoise();audio.play().catch(audioError)};pauseTimer=setTimeout(()=>{const resume=pauseResume;pauseResume=null;resume?.()},750)}});audio.addEventListener('ended',()=>finishAudio(m.duration),{once:true});audio.addEventListener('error',audioError,{once:true})}
 function playAudio(start,end,rate,onDone){stop();const m=D()[state.index];state.listens++;state.playing=true;state.position=start;updatePlayer();audio=new Audio(m.audioSrc);audio.muted=!state.sound;audio.preload='auto';audio.playbackRate=rate;audio.addEventListener('loadedmetadata',()=>{audio.currentTime=start;startNoise();audio.play().catch(audioError)},{once:true});audio.addEventListener('timeupdate',()=>{if(!audio)return;state.position=Math.min(end,audio.currentTime);updatePlayer();if(audio.currentTime>=end)finishAudio(end,onDone)});audio.addEventListener('ended',()=>finishAudio(end,onDone),{once:true});audio.addEventListener('error',audioError,{once:true})}
 function updatePlayer(){const m=D()[state.index],wave=root.querySelector('.wave'),clock=root.querySelector('.transport>span');wave?.style.setProperty('--pos',state.position/m.duration*100+'%');if(clock)clock.textContent=`${fmt(state.position)} / ${fmt(m.duration)}`;root.querySelector('.wave')?.classList.toggle('active',state.playing)}
 function startNoise(){stopNoise();if(!state.sound)return;try{noiseContext=new (window.AudioContext||window.webkitAudioContext)();const length=noiseContext.sampleRate*2,buffer=noiseContext.createBuffer(1,length,noiseContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*.16;noiseSource=noiseContext.createBufferSource();const filter=noiseContext.createBiquadFilter(),gain=noiseContext.createGain();filter.type='bandpass';filter.frequency.value=1700;filter.Q.value=.7;gain.gain.value=.075;noiseSource.buffer=buffer;noiseSource.loop=true;noiseSource.connect(filter).connect(gain).connect(noiseContext.destination);noiseSource.start()}catch(e){noiseContext=null;noiseSource=null}}
 function stopNoise(){try{noiseSource?.stop();noiseContext?.close()}catch(e){}noiseSource=null;noiseContext=null}
 function finishAudio(end,done){if(!audio)return;audio.pause();audio=null;stopNoise();state.position=end;if(done){done()}else{state.playing=false;updatePlayer()}}
 function audioError(){if(audio){audio.pause();audio=null}stopNoise();state.playing=false;feedback('Не удалось загрузить аудиозапись. Обнови страницу и повтори попытку.','bad')}
 function feedback(t,c){const f=root.querySelector('.feedback');if(f){f.className='feedback '+c;f.innerHTML=t}}
 function check(){if(state.messages[state.index].done){feedback('Это сообщение уже расшифровано.','good');return}if(!state.input.trim()){feedback('Сначала введи услышанное сообщение.','bad');return}state.attempts++;state.messages[state.index].attempts=state.attempts;state.messages[state.index].input=state.input;const result=C().compare(D()[state.index].transcript,state.input);state.lastAccuracy=result.accuracy;if(result.exact){state.score+=C().transcriptPoints(state.attempts);tone(880,.15);comprehension(result.accuracy)}else{tone(180,.12);const errors=result.words.filter(w=>w.status!=='correct').length;feedback(`<b>${errors} ${errors===1?'ошибка':'ошибок'} · точность ${result.accuracy}%</b><div class="word-feedback">${result.words.map(w=>`<span class="${w.status}">${w.status==='missing'?'____':esc(w.actual||w.expected)}</span>`).join(' ')}</div>${state.attempts>=3?'<button data-action="reveal">Показать ответ</button>':'Прослушай запись ещё раз и исправь текст.'}`,'bad')}}
 function comprehension(acc){const m=D()[state.index];state.status='question';root.querySelector('.signal-simple').innerHTML=`<section class="question-panel"><p>SIGNAL DECODED</p><h2>Точность: ${acc}%</h2><blockquote>${esc(m.transcript)}</blockquote><span>ПРОВЕРКА ПОНИМАНИЯ</span><h3>${esc(m.question.prompt)}</h3><div>${m.question.options.map((o,i)=>`<button data-option="${i}">${esc(o)}</button>`).join('')}</div><div class="feedback"></div></section>`}
 function answer(i){const m=D()[state.index],ok=i===m.question.correct;if(ok){state.score+=100;tone(950);complete(true)}else{tone(170);feedback(`Неверно. ${esc(m.question.explanation)}`,'bad');root.querySelectorAll('[data-option]').forEach(x=>x.disabled=true);setTimeout(()=>complete(false),1100)}}
 function complete(comp){const saved=state.messages[state.index];saved.input=state.input;saved.attempts=state.attempts;saved.hints=state.hints;saved.accuracy=state.lastAccuracy;saved.done=true;state.progress.push({index:state.index,accuracy:state.lastAccuracy,attempts:state.attempts,hints:state.hints,comp});const allDone=state.messages.every(x=>x.done);root.querySelector('.signal-simple').innerHTML=`<section class="message-complete"><p>MESSAGE ${state.index+1} COMPLETE</p><h2>Сигнал принят</h2><div><span>Расшифровка <b>+${C().transcriptPoints(state.attempts)}</b></span><span>Понимание смысла <b>+${comp?100:0}</b></span><span>Прослушиваний <b>${state.listens}</b></span><span>Подсказка <b>${state.hints?'использована':'нет'}</b></span></div><button data-action="next">${allDone?'ОТКРЫТЬ ОТЧЁТ':'К СЛЕДУЮЩЕМУ СИГНАЛУ'} →</button></section>`}
 function next(){if(state.messages.every(x=>x.done)){if(state.progress.every(x=>x.accuracy===100))state.score+=250;const best=+(localStorage.getItem('signalInterceptBest')||0);if(state.score>best)localStorage.setItem('signalInterceptBest',state.score);localStorage.setItem('signalInterceptComplete','yes');window.dispatchEvent(new Event('signal-intercept-complete'));state.status='results';render();return}for(let step=1;step<=5;step++){const target=(state.index+step)%5;if(!state.messages[target].done){switchMessage(target,true);return}}}
 function results(){const avg=Math.round(state.progress.reduce((a,x)=>a+x.accuracy,0)/5),hard=state.progress.slice().sort((a,b)=>a.accuracy-b.accuracy)[0].index;return `<section class="signal-results"><p>MISSION COMPLETE</p><h2>Все сообщения<br>расшифрованы</h2><div class="report"><span>ОБЩИЙ СЧЁТ <b>${state.score}</b></span><span>ТОЧНОСТЬ <b>${avg}%</b></span><span>ПРОСЛУШИВАНИЙ <b>${state.listens}</b></span><span>ПОДСКАЗОК <b>${state.progress.reduce((a,x)=>a+x.hints,0)}</b></span><span>РАСШИФРОВАНО <b>5 / 5</b></span><span>СЛОЖНАЯ ФРАЗА <b>Message ${hard+1}</b></span></div><p>Ты потренировал понимание связной речи, сокращений и деталей в английских сообщениях.</p><div><button data-action="restart">СЫГРАТЬ ЕЩЁ РАЗ</button><button data-action="close">ВЕРНУТЬСЯ К ДЕЛАМ</button></div></section>`}
 window.SignalIntercept={start,stop};
})();








