(function(){
 const contacts=[
  {id:'mother',name:'Мама',role:'СЕМЬЯ',avatar:1,preview:'Alex, where are you?',time:'18:52',chat:[['date','MONDAY'],['in','Do you want pasta or soup tonight?'],['out','Pasta, please. I’ll be home after class.'],['in','Don’t forget your jacket again.'],['date','TODAY'],['in','I bought those train snacks you like.'],['out','Thanks, Mum. See you later.'],['in','Alex, where are you? Please call me.']]},
  {id:'jamie',name:'Джейми Коул',role:'ДРУГ АЛЕКСА',avatar:2,preview:'Send me the homework later',time:'16:42',chat:[['date','TUESDAY'],['in','Did you finish the history presentation?'],['out','Almost. The last slide looks terrible.'],['in','It always does. That is your style.'],['out','Very funny.'],['date','TODAY'],['in','Football on Saturday?'],['out','If I survive the English test.'],['in','Deal. Send me the homework later.']]},
  {id:'anna',name:'Анна Рид',role:'БИБЛИОТЕКАРЬ',image:'assets/evidence-witness-anna.png',preview:'Voice message · 0:10',time:'18:22',suspect:true,gap:'blue atlas',note:'Анна рассказала Алексу, где лежит план старого крыла.',text:'I found the school map you asked about. It is inside the blue atlas on the second shelf.',voices:[['Your book is waiting at the front desk. I renewed it for another week.','0:07','anna-reed-1.mp3','Просьба продлить книгу. Ничего необычного.'],['I found the school map you asked about. It is inside the blue atlas on the second shelf.','0:10','anna-reed-2.mp3','План школы был спрятан в атласе… Почему его нельзя было просто выдать Алексу?'],['Please put everything back before the library closes, Alex.','0:06','anna-reed-3.mp3','Анна ожидала, что Алекс ещё вернётся в библиотеку. Что именно он должен был вернуть?']],chat:[['date','LAST FRIDAY'],['out','Could you renew my history book?'],['voice',0],['out','Thank you, Mrs Reed.'],['date','TODAY'],['in','I checked the catalogue for you.'],['voice',1],['out','Found it. Thanks.'],['voice',2],['out','I will.']]},
  {id:'mark',name:'Марк Белл',role:'ЗАВХОЗ',image:'assets/evidence-witness-mark.png',preview:'Voice message · 0:11',time:'18:31',suspect:true,gap:'science stairs',note:'Марк знал, что Алекс искал старую комнату.',text:'The main corridor is a mess tonight. If you are still looking for that old room, try the quieter way past the science stairs.',voices:[['The projector is working again. Tell your teacher not to move the cable.','0:07','mark-bell-1.mp3','Похоже на простую рабочую переписку.'],['The main corridor is a mess tonight. If you are still looking for that old room, try the quieter way past the science stairs.','0:11','mark-bell-2.mp3','«Та старая комната»… Значит, Марк понимал, что именно искал Алекс. Откуда?'],['If you borrowed anything from the maintenance desk, put it back before you leave.','0:08','mark-bell-3.mp3','Что Алекс мог взять со стола завхоза? Марк намеренно не называет предмет.']],chat:[['date','LAST WEEK'],['out','The projector stopped again.'],['voice',0],['out','Okay, I’ll tell her.'],['date','TODAY'],['in','Are you still at school?'],['out','Yes. Why?'],['voice',1],['out','Got it. Thanks.'],['voice',2],['out','I won’t forget.']]},
  {id:'leo',name:'Лео Грант',role:'ОХРАННИК',image:'assets/evidence-witness-leo.png',preview:'Voice message · 0:09',time:'18:47',suspect:true,gap:'west stairwell',note:'Лео предупредил Алекса, какой лестницей можно воспользоваться вечером.',text:'The main hall is being cleaned. The west stairwell is open if you need to go upstairs.',voices:[['Your blue scarf is still at the security desk. Pick it up whenever you can.','0:07','leo-grant-1.mp3','Лео и раньше общался с Алексом. Пока это выглядит естественно.'],['The main hall is being cleaned. The west stairwell is open if you need to go upstairs.','0:09','leo-grant-2.mp3','Лео направил Алекса наверх в обход главного коридора. Просто помог — или хотел изменить его маршрут?'],['I will lock the side door at seven, so do not stay too long.','0:08','leo-grant-3.mp3','Лео знал, что Алекс всё ещё в школе. Почему он собирался закрыть боковую дверь?']],chat:[['date','MONDAY'],['voice',0],['out','I’ve been looking for it. Thanks!'],['date','TODAY'],['in','Still waiting for your train?'],['out','I have time. I need to get something upstairs.'],['voice',1],['out','Okay.'],['voice',2],['out','I’ll be quick.']]}
 ];
 const repairGaps={anna:[['front desk'],['school map','second'],['back','library']],mark:[['working'],['old room','science'],['anything','leave']],leo:[['blue scarf'],['west'],['at seven']]};
 let root,onClose,s,realAudio;
 const esc=v=>{const x=document.createElement('span');x.textContent=v;return x.innerHTML};
 const numberWords={zero:'0',one:'1',two:'2',three:'3',four:'4',five:'5',six:'6',seven:'7',eight:'8',nine:'9',ten:'10',eleven:'11',twelve:'12',thirteen:'13',fourteen:'14',fifteen:'15',sixteen:'16',seventeen:'17',eighteen:'18',nineteen:'19',twenty:'20'};
 const normalize=x=>(x||'').toLowerCase().trim().replace(/(\d)\s*[:.]\s*(\d)/g,'$1 $2').replace(/\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty)\b/g,w=>numberWords[w]).replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
 const stored=()=>{try{return JSON.parse(localStorage.getItem('alexPhoneMessages')||'[]')}catch(e){return[]}};
 const storedRepairs=()=>{try{return JSON.parse(localStorage.getItem('alexPhoneRepairs')||'[]')}catch(e){return[]}};
 function fresh(){const valid=new Set(Object.keys(repairGaps).flatMap(id=>[0,1,2].map(i=>`${id}-${i}`))),repaired=new Set(storedRepairs().filter(x=>valid.has(x))),saved=new Set(Object.keys(repairGaps).filter(id=>[0,1,2].every(i=>repaired.has(`${id}-${i}`))));return{view:'intro',contact:null,playing:false,repairOpen:null,inputs:[],feedback:'',heard:new Set(repaired),repaired,saved}}
 function start(el,close){root=el;onClose=close;s=fresh();render()}
 function stopAudio(){if(realAudio){realAudio.pause();realAudio=null}window.speechSynthesis?.cancel();if(s)s.playing=false}
 function stop(){stopAudio()}
 function avatar(c,tag='i'){return `<${tag} class="phone-avatar ${c.avatar!==undefined?`avatar-${c.avatar}`:''}" ${c.image?`style="background-image:url('${c.image}');background-size:cover;background-position:center top"`:''} aria-hidden="true"></${tag}>`}
 function render(){stopAudio();root.innerHTML=`<div class="phone-game">${phoneFixes()}${phonePositionFixes()}${phoneAnalysisFixes()}${repairFixes()}${resultsFixes()}${s.view==='intro'?intro():s.view==='results'?results():phone()}</div>`;bind()}
 function phonePositionFixes(){return `<style>.phone-game .phone-case-head,.phone-game .mobile-conversation>header,.phone-game .mobile-chats>header{position:static!important;inset:auto!important;width:auto!important;z-index:auto!important}.phone-game .phone-stage{padding-top:0!important;overflow:hidden!important}.phone-game .phone-case-head{box-sizing:border-box!important;flex:none!important}.phone-game .phone-device{position:relative!important;top:auto!important;bottom:auto!important;transform:none!important}</style>`}
 function phoneFixes(){return `<style>.phone-game .phone-hand-art>div{display:none!important}.phone-game .phone-device{box-sizing:border-box!important;height:620px!important}.phone-game .device-screen{box-sizing:border-box!important}.phone-game .mobile-conversation{background-color:#72afe0!important;background-image:linear-gradient(#2479b64d,#2479b64d),url('assets/signal-intercept/messenger-wallpaper-blue-v1.png')!important;background-size:auto,330px auto!important;background-repeat:repeat!important}.phone-game .message-thread{overflow-x:hidden!important;padding:20px 20px 24px!important}.phone-game .bubble{max-width:78%!important;background:#fff!important;color:#25313b!important;box-shadow:0 1px 2px #24445c44!important}.phone-game .bubble:before{border-right-color:#fff!important;border-bottom-color:#fff!important}.phone-game .bubble.out{background:#d8f0ff!important;color:#1e3444!important}.phone-game .bubble.out:before{border-right-color:transparent!important;border-bottom-color:#d8f0ff!important;border-left-color:#d8f0ff!important}.phone-game .chat-date{background:#337fadcc!important;color:#fff!important}.phone-game .voice-message{max-width:78%!important;background:#fff!important;color:#294154!important}.phone-game .mobile-conversation>header,.phone-game .mobile-status,.phone-game .mobile-chats{background:#fff!important;color:#24323c!important}.phone-game .mobile-conversation>header b,.phone-game .mobile-chats>header b{color:#24323c!important}.phone-game .mobile-chat-list>button{background:#fff!important;color:#24323c!important}.phone-game .mobile-chat-list>button:hover{background:#edf6fc!important}.phone-game .mobile-search{background:#edf1f4!important;color:#84919a!important}.phone-game .mobile-conversation>footer{background:#fff!important;color:#8b979f!important}</style>`}
 function intro(){return `<section class="phone-intro"><div class="phone-hand-art"></div><div class="phone-intro-copy"><h2>Последние<br>сообщения</h2><span>Прочитай переписки и восстанови повреждённые голосовые.</span><button data-action="begin">ОТКРЫТЬ ТЕЛЕФОН</button></div></section>`}
 function phoneAnalysisFixes(){return `<style>.phone-game .phone-workspace{display:grid;grid-template-columns:390px 300px;gap:28px;justify-content:center;align-items:start}.phone-game .phone-workspace>.phone-device{margin:14px 0 0!important}.phone-game .phone-side{margin-top:72px;display:grid;gap:14px}.phone-game .detective-panel{margin:0;min-height:245px;padding:22px;border:1px solid #665031;background:linear-gradient(145deg,#17120d,#090806);box-shadow:0 18px 45px #000}.phone-game .detective-panel>small{color:#b48e4c;font-size:8px;letter-spacing:2px}.phone-game .detective-panel h3{margin:7px 0 17px;color:#e8d9bd;font:27px 'Cormorant Garamond'}.phone-game .detective-panel .thought-empty{color:#82796b;font-size:11px;line-height:1.55}.phone-game .detective-thought{position:relative;margin:0 0 12px;padding:12px 13px 12px 16px;border-left:2px solid #5e9bc4;background:#101820;color:#cbd2d5;font:13px/1.5 Georgia;animation:thoughtIn .35s ease}.phone-game .detective-thought b{display:block;margin-bottom:5px;color:#6eacd4;font:8px Inter;letter-spacing:1.3px}@keyframes thoughtIn{from{opacity:0;transform:translateY(7px)}}@media(max-width:850px){.phone-game .phone-workspace{grid-template-columns:1fr}.phone-game .phone-workspace>.phone-device{width:min(340px,calc(100vw - 16px))!important;margin:14px auto 0!important}.phone-game .phone-side{width:min(340px,calc(100vw - 24px));margin:16px auto;display:flex;flex-direction:column}.phone-game .phone-side .audio-repair{order:1}.phone-game .detective-panel{order:2;width:auto;min-height:0}.phone-game .audio-repair blockquote{font-size:15px!important}.phone-game .repair-fields{grid-template-columns:1fr!important}.phone-game .repair-fields input{font-size:16px!important}.phone-game .phone-case-head{padding-left:12px!important;padding-right:50px!important}.phone-game .phone-case-head>div b{font-size:15px!important}.phone-game .phone-case-head>button{padding:7px!important;font-size:9px!important}}</style>`}
 function repairFixes(){return `<style>.phone-game .phone-side .audio-repair{position:relative;z-index:auto;inset:auto;padding:16px;border:1px solid #365b78;border-radius:0;background:#111923;box-shadow:0 16px 36px #000}.phone-game .audio-repair blockquote{font-size:12px;line-height:1.65}.phone-game .repair-blank{display:inline-grid;min-width:25px;min-height:20px;margin:0 2px;padding:0 5px;place-items:center;border-bottom:1px solid #68aee0;color:#68aee0;font:10px Inter;transition:.18s}.phone-game .repair-blank.empty{display:inline-flex;gap:4px;padding:0;border:0;vertical-align:middle}.phone-game .repair-blank.empty i{display:inline-grid;min-width:28px;height:20px;place-items:center;border-bottom:1px solid #68aee0;color:#68aee0;font:normal 9px Inter}.phone-game .repair-blank.correct{border-color:#54bd78;background:#173a26;color:#81dfa0}.phone-game .repair-blank.wrong{border-color:#d35d56;background:#421e20;color:#ff9b94}.phone-game .repair-fields{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px!important}.phone-game .repair-fields label{display:grid;grid-template-columns:24px minmax(0,1fr);align-items:center;border:1px solid #40566a;background:#0e1621}.phone-game .repair-fields label>span{display:grid;height:100%;place-items:center;border-right:1px solid #40566a;color:#68aee0;font-size:9px}.phone-game .repair-fields input{width:100%;box-sizing:border-box;border:0!important;background:transparent!important}.phone-game .repair-submit{width:100%;margin-top:8px}</style>`}
 function resultsFixes(){return `<style>.phone-game .phone-results{padding:48px 24px;place-content:center}.phone-game .phone-results>p{margin:0 0 12px;font-size:11px}.phone-game .phone-results h2{margin:0 0 14px;font-size:58px;line-height:1}.phone-game .phone-results>span{max-width:720px;font-size:17px;line-height:1.55}.phone-game .phone-results>div{width:min(720px,88vw);margin:26px auto 0;grid-template-columns:1fr;gap:9px}.phone-game .phone-results article{min-height:92px;padding:13px 18px;display:grid;grid-template-columns:64px 145px minmax(0,1fr);align-items:center;gap:16px}.phone-game .phone-results article .phone-avatar{width:60px;height:60px;margin:0}.phone-game .phone-results article small{font-size:16px;line-height:1.25}.phone-game .phone-results article b{margin:0;font-size:14px;line-height:1.5}.phone-game .phone-results>button{width:310px;margin:22px auto 0;padding:16px 24px;font-size:14px}@media(max-width:650px){.phone-game .phone-results h2{font-size:42px}.phone-game .phone-results>span{font-size:14px}.phone-game .phone-results>div{width:100%}.phone-game .phone-results article{grid-template-columns:55px 1fr;gap:10px}.phone-game .phone-results article .phone-avatar{width:52px;height:52px}.phone-game .phone-results article b{grid-column:2}.phone-game .phone-results>button{width:min(310px,100%)}}</style>`}
 function phone(){const c=contacts.find(x=>x.id===s.contact);return `<section class="phone-stage"><header class="phone-case-head"><div><b>THE MISSING STUDENT</b><small>ТЕЛЕФОН АЛЕКСА</small></div><span>СОХРАНЕНО ${s.saved.size} / 3</span><button data-action="leave">К МАТЕРИАЛАМ</button></header><div class="phone-workspace"><main class="phone-device"><div class="device-speaker"></div><div class="device-screen"><div class="mobile-status"><b>18:52</b><span>•••</span></div>${c?conversation(c):chatList()}</div><div class="device-home"></div></main><div class="phone-side">${detectivePanel(c)}${repairSide(c)}</div></div></section>`}
 function detectivePanel(c){return `<aside class="detective-panel"><small>ЗАМЕТКИ ДЕТЕКТИВА</small><h3>${c?.suspect?c.name:'Анализ сообщений'}</h3><div class="detective-notes">${detectiveNotes(c)}</div></aside>`}
 function detectiveNotes(c){if(!c?.suspect)return '';return c.voices.map((v,i)=>s.heard.has(`${c.id}-${i}`)?`<article class="detective-thought"><b>ЗАПИСЬ ${i+1}</b>${esc(v[3])}</article>`:'').join('')}
 function chatList(){return `<section class="mobile-chats"><header><b>Чаты</b><span>Телефон Алекса</span></header><div class="mobile-search">Поиск</div><div class="mobile-chat-list">${contacts.map(x=>`<button data-contact="${x.id}">${avatar(x)}<span><b>${x.name}</b><small>${x.preview}</small></span><time>${x.time}</time>${x.suspect&&!s.saved.has(x.id)?'<em></em>':''}</button>`).join('')}</div></section>`}
 function conversation(c){return `<section class="mobile-conversation"><header><button data-action="back-chats" aria-label="Назад">‹</button>${avatar(c)}<span><b>${c.name}</b><small>${c.role}</small></span></header><div class="message-thread">${c.chat.map(m=>m[0]==='voice'?voice(c,m[1]):m[0]==='date'?`<div class="chat-date">${esc(m[1])}</div>`:`<div class="bubble ${m[0]}">${esc(m[1])}</div>`).join('')}</div><footer><span>Сообщение</span><i>•••</i></footer></section>`}
 function repairSide(c){if(!c?.suspect||!s.repairOpen?.startsWith(`${c.id}-`))return '';return repair(c,+s.repairOpen.split('-')[1])}
 function voice(c,index){const key=`${c.id}-${index}`,v=c.voices[index],active=s.playing===key,damaged=c.suspect&&!s.repaired.has(key);return `<button class="voice-message ${active?'playing':''} ${damaged?'damaged':''}" data-action="play" data-voice="${index}"><span class="voice-play">${active?'Ⅱ':'▶'}</span><i>${Array.from({length:28},(_,i)=>`<b style="height:${8+((i+index*5)*13%24)}px"></b>`).join('')}</i><time>${v[1]}</time>${damaged?'<em>ФРАГМЕНТ ПОВРЕЖДЁН</em>':''}</button>`}
 function blankSlots(answer,index){return answer.trim().split(/\s+/).map((_,word)=>`<i>${word===0?index+1:''}</i>`).join('')}
 function repairText(text,gaps,values=s.inputs){let result=esc(text);gaps.forEach((gap,i)=>{const value=values[i]||'',state=value?(normalize(value)===normalize(gap)?'correct':'wrong'):'empty';result=result.replace(new RegExp(esc(gap),'i'),`<strong class="repair-blank ${state}" data-gap-preview="${i}">${value?esc(value):blankSlots(gap,i)}</strong>`)});return result}
 function repair(c,index){const key=`${c.id}-${index}`,gaps=repairGaps[c.id][index],v=c.voices[index],restored=s.repaired.has(key),values=restored?gaps:s.inputs;return `<div class="audio-repair ${restored?'restored':''}"><button class="repair-close" data-action="close-repair">ЗАКРЫТЬ</button><small>${restored?'ГОЛОСОВОЕ ВОССТАНОВЛЕНО':'ВОССТАНОВЛЕНИЕ ГОЛОСОВОГО'}</small><blockquote>${repairText(v[0],gaps,values)}</blockquote>${restored?'':`<div class="repair-fields">${gaps.map((_,i)=>`<label><span>${i+1}</span><input data-gap="${i}" autocomplete="off" value="${esc(s.inputs[i]||'')}" aria-label="Фрагмент ${i+1}"></label>`).join('')}</div><button class="repair-submit" data-action="save">ВОССТАНОВИТЬ</button><p class="${s.feedback?'visible':''}">${esc(s.feedback)}</p>`}</div>`}
 function results(){return `<section class="phone-results"><p>ТЕЛЕФОН АЛЕКСА · ИЗВЛЕЧЕНО 3 / 3</p><h2>Сообщения сохранены</h2><span>Анна Рид, Марк Белл и Лео Грант знали разные части планов Алекса. Их сообщения можно будет сравнить с показаниями в финальном расследовании.</span><div>${contacts.filter(x=>x.suspect).map(x=>`<article>${avatar(x)}<small>${x.name}</small><b>${x.note}</b></article>`).join('')}</div><button data-action="close">ЗАВЕРШИТЬ ГЛАВУ</button></section>`}
 function bind(){root.onclick=click;root.querySelectorAll('[data-gap]').forEach(input=>{input.oninput=e=>{const i=+e.target.dataset.gap,value=e.target.value;s.inputs[i]=value;const preview=root.querySelector(`[data-gap-preview="${i}"]`),c=contacts.find(x=>x.id===s.contact),index=+s.repairOpen.split('-')[1],answer=repairGaps[c.id][index][i];if(preview){if(value)preview.textContent=value;else preview.innerHTML=blankSlots(answer,i);preview.classList.toggle('empty',!value);preview.classList.toggle('correct',!!value&&normalize(value)===normalize(answer));preview.classList.toggle('wrong',!!value&&normalize(value)!==normalize(answer))}};input.onkeydown=e=>{if(e.key==='Enter')check()}})}
 function click(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.contact){s.contact=b.dataset.contact;s.repairOpen=null;s.inputs=[];s.feedback='';render();return}const a=b.dataset.action;if(a==='begin'){s.view='phone';render()}else if(a==='back-chats'){s.contact=null;s.repairOpen=null;render()}else if(a==='play')playCurrent(+b.dataset.voice);else if(a==='close-repair'){s.repairOpen=null;s.inputs=[];s.feedback='';render()}else if(a==='save')check();else if(a==='leave'||a==='close')onClose()}
 function playCurrent(index){const c=contacts.find(x=>x.id===s.contact);if(!c?.suspect)return;const key=`${c.id}-${index}`,sameRepair=s.repairOpen===key;s.repairOpen=key;if(!sameRepair)s.inputs=s.repaired.has(key)?[...repairGaps[c.id][index]]:[];s.feedback='';render();playVoice(c,index)}
 function playVoice(c,index){const key=`${c.id}-${index}`;if(s.playing===key){stopAudio();return}stopAudio();s.playing=key;const v=c.voices[index],button=root.querySelector(`[data-voice="${index}"]`),finish=()=>{s.playing=false;button?.classList.remove('playing')};button?.classList.add('playing');realAudio=new Audio(`assets/signal-intercept/audio/${v[2].replace(/\.mp3$/,'.wav')}`);realAudio.onended=finish;realAudio.onerror=()=>{realAudio=null;const u=new SpeechSynthesisUtterance(v[0]);u.lang='en-GB';u.rate=.88;u.pitch=.92;u.onend=finish;window.speechSynthesis?.speak(u)};realAudio.play().catch(()=>realAudio?.onerror?.())}
 function check(){const c=contacts.find(x=>x.id===s.contact),index=+s.repairOpen.split('-')[1],key=`${c.id}-${index}`,gaps=repairGaps[c.id][index],correct=gaps.every((gap,i)=>normalize(s.inputs[i])===normalize(gap));if(!correct){s.feedback='Запись не восстановлена.';const p=root.querySelector('.audio-repair p');if(p){p.textContent=s.feedback;p.classList.add('visible')}return}s.repaired.add(key);s.heard.add(key);localStorage.setItem('alexPhoneRepairs',JSON.stringify([...s.repaired]));if([0,1,2].every(i=>s.repaired.has(`${c.id}-${i}`)))s.saved.add(c.id);localStorage.setItem('alexPhoneMessages',JSON.stringify([...s.saved]));localStorage.setItem('alexPhoneEvidenceCount',s.saved.size);window.dispatchEvent(new CustomEvent('alex-phone-updated',{detail:{count:s.saved.size}}));s.repairOpen=null;s.inputs=[];s.feedback='';render();if(s.saved.size===3){localStorage.setItem('signalInterceptComplete','yes');window.dispatchEvent(new Event('signal-intercept-complete'));setTimeout(()=>{s.view='results';render()},1800)}}
 window.SignalIntercept={start,stop,getEvidence(){return contacts.filter(x=>x.suspect).map(x=>({id:x.id,title:`Голосовое · ${x.name}`,text:x.text,note:x.note,image:x.image,found:s?.saved.has(x.id)||stored().includes(x.id)}))}};
})();
