const cases=[
 {level:'ГЛАВА 1',file:'',title:'The Night Archive',desc:'Проникни в архив, избегай патруля и найди следы Алекса в запертых шкафах.',action:'НАЧАТЬ РАССЛЕДОВАНИЕ',img:'assets/school.png',type:'verbcase'},
 {level:'ГЛАВА 2',file:'',title:'The Last Messages',desc:'Исследуй найденный в архиве телефон Алекса и восстанови повреждённые голосовые сообщения.',action:'ОТКРЫТЬ ТЕЛЕФОН',img:'assets/signal-intercept/alex-phone-case-v1.png',type:'signal'},
 {level:'ГЛАВА 3',file:'',title:'The Evidence Room',desc:'Сопоставь найденные факты и установи, кто скрывает правду об исчезновении Алекса.',action:'РАСКРЫТЬ ДЕЛО',img:'assets/evidence-room-room.png',type:'evidence'}];
const grid=document.querySelector('#caseGrid'),modal=document.querySelector('#modal'),gameBody=document.querySelector('#gameBody');
grid.innerHTML=cases.map((c,i)=>{const done=c.type==='signal'?localStorage.getItem('signalInterceptComplete')==='yes':c.type==='evidence'?localStorage.getItem('evidenceRoomComplete')==='yes':c.type==='verbcase'&&localStorage.getItem('missingStudentComplete')==='yes';return `<article class="dossier ${done?'complete':''} ${c.locked?'locked':''}" ${c.locked?'aria-disabled="true"':`tabindex="0" data-open="${i}"`}><span class="tab">${c.level}</span>${c.file?`<span class="file-no">${c.file}</span>`:''}<div class="case-inner"><div class="photo"><img src="${c.img}" alt="Иллюстрация дела ${c.title}"></div><div class="case-copy"><h3>${c.title}</h3><p>${c.desc}</p></div></div><span class="mark">${c.locked?'ACCESS<br>DENIED':`CASE<br>${done?'COMPLETE':'ACTIVE'}`}</span><button class="open-case" ${c.locked?'disabled':''}>${c.locked?'ДОСТУП ЗАКРЫТ':done?'ПРОЙТИ ЕЩЁ РАЗ':c.action}</button></article>`}).join('');
const homeEvidenceGrid=document.querySelector('#homeEvidenceGrid'),evidenceProgress=document.querySelector('#evidenceProgress'),materialsModal=document.querySelector('#materialsModal');
function evidenceState(){return window.MissingStudent?.getEvidence?.()||{count:0,total:8,items:[]}}
function renderHomeEvidence(){const data=evidenceState();evidenceProgress.textContent=`${data.count} / ${data.total}`;homeEvidenceGrid.innerHTML=Array.from({length:data.total},(_,i)=>{const item=data.items[i],found=i<data.count,x=(i%4)*33.333,y=Math.floor(i/4)*100;return `<button class="home-evidence ${found?'found':'locked'} item-${i}" ${found?`data-home-evidence="${i}" aria-label="Открыть улику: ${escapeHtml(item.title)}"`:'disabled aria-label="Улика еще не найдена"'} style="--evidence-x:${x}%;--evidence-y:${y}%"><i></i><span>${String(i+1).padStart(2,'0')}</span><b>${found?escapeHtml(item.title):'НЕ НАЙДЕНО'}</b></button>`}).join('')}
function renderPhoneEvidence(){let block=document.querySelector('#phoneEvidenceBlock');if(!block){block=document.createElement('div');block.id='phoneEvidenceBlock';block.className='phone-materials';homeEvidenceGrid.after(block)}const items=window.SignalIntercept?.getEvidence?.()||[];const found=items.filter(x=>x.found).length;block.innerHTML=`<div class="phone-materials-head"><div><span>ТЕЛЕФОН АЛЕКСА</span><h3>Сохранённые голосовые</h3></div><strong>${found} / 3</strong></div><div class="phone-materials-grid">${items.map((x,i)=>`<button class="phone-material ${x.found?'found':'locked'}" ${x.found?`data-phone-evidence="${i}"`:'disabled'}><i style="background-image:url('${x.image}')!important;background-size:cover!important;background-position:center top!important"></i><span>${String(i+1).padStart(2,'0')}</span><b>${x.found?escapeHtml(x.title):'НЕ ВОССТАНОВЛЕНО'}</b></button>`).join('')}</div>`}
function openHomeEvidence(index){const data=evidenceState(),item=data.items[index];if(!item||index>=data.count)return;document.querySelector('#materialTag').textContent=item.tag;document.querySelector('#materialTitle').textContent=item.title;document.querySelector('#materialText').textContent=item.text;document.querySelector('#materialConclusion').textContent=item.conclusion;const image=document.querySelector('#materialImage');image.className=`material-image item-${index}`;image.style.backgroundPosition=`${(index%4)*33.333}% ${Math.floor(index/4)*100}%`;materialsModal.classList.add('active');materialsModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function openPhoneEvidence(index){const item=window.SignalIntercept?.getEvidence?.()[index];if(!item?.found)return;document.querySelector('#materialTag').textContent='ТЕЛЕФОН АЛЕКСА · ГОЛОСОВОЕ СООБЩЕНИЕ';document.querySelector('#materialTitle').textContent=item.title;document.querySelector('#materialText').textContent=`“${item.text}”`;document.querySelector('#materialConclusion').textContent=item.note;const image=document.querySelector('#materialImage');image.className='material-image phone-contact';image.style.backgroundImage=`url('${item.image}')`;image.style.backgroundSize='cover';image.style.backgroundPosition='center 25%';materialsModal.classList.add('active');materialsModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeHomeEvidence(){materialsModal.classList.remove('active');materialsModal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelector('#caseMaterials').onclick=e=>{const archive=e.target.closest('[data-home-evidence]');if(archive)openHomeEvidence(+archive.dataset.homeEvidence)};document.querySelectorAll('[data-material-close]').forEach(x=>x.onclick=closeHomeEvidence);window.addEventListener('missing-student-evidence-updated',renderHomeEvidence);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&materialsModal.classList.contains('active'))closeHomeEvidence()});renderHomeEvidence();
const carousel=document.querySelector('.case-carousel');
document.querySelector('.case-arrow.prev').onclick=()=>grid.scrollBy({left:-grid.clientWidth*.82,behavior:'smooth'});
document.querySelector('.case-arrow.next').onclick=()=>grid.scrollBy({left:grid.clientWidth*.82,behavior:'smooth'});
let caseDrag=null,blockCaseClick=false;
grid.addEventListener('pointerdown',e=>{if(e.button!==0)return;caseDrag={x:e.clientX,left:grid.scrollLeft,moved:false,id:e.pointerId,card:e.target.closest('.dossier[data-open]'),launchButton:e.target.closest('.open-case')};grid.setPointerCapture(e.pointerId)});
grid.addEventListener('pointermove',e=>{if(!caseDrag||e.pointerId!==caseDrag.id)return;const distance=e.clientX-caseDrag.x;if(Math.abs(distance)>5){caseDrag.moved=true;grid.classList.add('dragging')}grid.scrollLeft=caseDrag.left-distance});
function finishCaseDrag(e){if(!caseDrag||e.pointerId!==caseDrag.id)return;const drag=caseDrag,mobile=matchMedia('(max-width:700px)').matches;blockCaseClick=true;caseDrag=null;grid.classList.remove('dragging');if(grid.hasPointerCapture(e.pointerId))grid.releasePointerCapture(e.pointerId);if(!drag.moved&&drag.card&&(!mobile||drag.launchButton))openGame(+drag.card.dataset.open);setTimeout(()=>{blockCaseClick=false},0)}
grid.addEventListener('pointerup',finishCaseDrag);grid.addEventListener('pointercancel',finishCaseDrag);
grid.addEventListener('click',e=>{if(blockCaseClick){e.preventDefault();e.stopPropagation()}},true);
window.addEventListener('evidence-room-complete',()=>{const card=grid.querySelector('.dossier[data-open="2"]');if(!card)return;card.classList.add('complete');card.querySelector('.mark').innerHTML='CASE<br>COMPLETE';card.querySelector('.open-case').textContent='ПРОЙТИ ЕЩЁ РАЗ'});
window.addEventListener('signal-intercept-complete',()=>{const card=grid.querySelector('.dossier[data-open="1"]');if(!card)return;card.classList.add('complete');card.querySelector('.mark').innerHTML='CASE<br>COMPLETE';card.querySelector('.open-case').childNodes[0].textContent='ПРОЙТИ ЕЩЁ РАЗ '});
window.addEventListener('missing-student-complete',()=>{const card=grid.querySelector('.dossier[data-open="0"]');if(!card)return;card.classList.add('complete');card.querySelector('.mark').innerHTML='CASE<br>COMPLETE';card.querySelector('.open-case').textContent='ПРОЙТИ ЕЩЁ РАЗ'});
window.addEventListener('open-evidence-room',()=>openGame(2));
const login=document.querySelector('.login'),nameModal=document.querySelector('#nameModal'),nameInput=document.querySelector('#detectiveName');
function escapeHtml(s){const x=document.createElement('span');x.textContent=s;return x.innerHTML}function avatarSrc(value=localStorage.getItem('detectiveAvatar')){return value==='male'?'assets/detective-avatar-male.png':'assets/detective-avatar.png'}function setDetective(name){if(name){login.classList.add('detective');login.title='Изменить имя или аватар';login.setAttribute('aria-label','Изменить имя или аватар');login.innerHTML=`<img src="${avatarSrc()}" alt=""><span>Детектив ${escapeHtml(name)}</span>`}}function openName(){nameModal.classList.add('active');nameInput.value=localStorage.getItem('detectiveName')||'';const avatar=localStorage.getItem('detectiveAvatar')||'female',choice=document.querySelector(`[name="detectiveAvatar"][value="${avatar}"]`);if(choice)choice.checked=true;setTimeout(()=>nameInput.focus(),30)}function closeName(){nameModal.classList.remove('active')}
setDetective(localStorage.getItem('detectiveName'));login.onclick=openName;document.querySelector('#nameForm').onsubmit=e=>{e.preventDefault();const n=nameInput.value.trim().replace(/\s+/g,' '),avatar=document.querySelector('[name="detectiveAvatar"]:checked')?.value||'female';if(n){localStorage.setItem('detectiveName',n);localStorage.setItem('detectiveAvatar',avatar);setDetective(n);closeName();showToast(`Добро пожаловать, детектив ${n}`)}};document.querySelectorAll('[data-name-close]').forEach(x=>x.onclick=closeName);
document.addEventListener('click',e=>{const scroll=e.target.closest('[data-scroll-cases]');if(scroll){document.querySelector('#cases')?.scrollIntoView({behavior:'smooth',block:'start'});return}const op=e.target.closest('[data-open]'),mobile=matchMedia('(max-width:700px)').matches;if(op&&(!mobile||e.target.closest('.open-case')))openGame(+op.dataset.open);if(e.target.closest('[data-close]'))closeGame(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(nameModal.classList.contains('active'))closeName();else if(modal.classList.contains('active'))closeGame(true)}if(e.key==='Enter'&&e.target.matches('.dossier'))openGame(+e.target.dataset.open)});
function openGame(i){const c=cases[i];const special=c.type==='evidence'||c.type==='signal'||c.type==='verbcase';document.querySelector('#gameLevel').textContent=special?'':`${c.file} / ${c.level}`;document.querySelector('#progress').textContent=special?'':'ДЕЛО ОТКРЫТО';gameBody.innerHTML=c.type==='find'?findGame(c):c.type==='cipher'?cipherGame(c):'';modal.classList.add('active');document.body.style.overflow='hidden';modal.querySelector('.game').classList.toggle('heist-modal',false);modal.querySelector('.game').classList.toggle('evidence-modal',c.type==='evidence');modal.querySelector('.game').classList.toggle('signal-modal',c.type==='signal');modal.querySelector('.game').classList.toggle('missing-modal',c.type==='verbcase');if(c.type==='evidence')EvidenceRoom.start(gameBody,()=>closeGame(false));else if(c.type==='signal')SignalIntercept.start(gameBody,()=>closeGame(false));else if(c.type==='verbcase')MissingStudent.start(gameBody,()=>closeGame(false));else bindSimple(c.type)}
function closeGame(ask,confirmed=false){const missingActive=document.querySelector('.ms-layout,.ms-platform-layout');if(missingActive&&!confirmed&&window.MissingStudent?.requestClose){MissingStudent.requestClose(()=>closeGame(false,true));return}if(window.MissingStudent)MissingStudent.stop();if(window.SignalIntercept)SignalIntercept.stop();modal.classList.remove('active');document.body.style.overflow='';gameBody.innerHTML=''}
function findGame(c){return `<h2>${c.title}</h2><p class="intro">Осмотри место исчезновения. Найди 3 активные точки.</p><div class="clue-scene" style="background-image:url('${c.img}')"><button class="clue" style="left:44%;top:77%" data-clue="notebook"></button><button class="clue" style="left:79%;top:39%" data-clue="locker"></button><button class="clue" style="left:17%;top:28%" data-clue="window"></button></div><div class="clue-list"><span class="chip">Найдено: <b id="found">0</b>/3</span></div><p class="feedback" id="feedback">Улики слегка пульсируют.</p>`}
function cipherGame(c){return `<h2>${c.title}</h2><p class="intro">Шифр: △ = TRUST, ○ = NO, □ = ONE. Как переводится «△ ○ □»?</p><div class="clue-scene" style="background-image:url('${c.img}')"></div><div class="choice-grid"><button data-answer="bad">Доверься всем</button><button data-answer="good">Не доверяй никому</button><button data-answer="bad">Никто не верит</button></div><p class="feedback" id="feedback">Выбери точный перевод.</p>`}
function bindSimple(type){if(type==='find'){let n=0;document.querySelectorAll('.clue').forEach(b=>b.onclick=()=>{if(!b.classList.contains('found')){b.classList.add('found');document.querySelector('#found').textContent=++n;if(n===3)win('Все улики найдены!')}})}if(type==='cipher')document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>b.dataset.answer==='good'?win('Послание расшифровано!'):document.querySelector('#feedback').textContent='Эта версия неверна.')}
function win(msg){document.querySelector('#feedback').textContent=msg;document.querySelector('#progress').textContent='ДЕЛО РАСКРЫТО ✓';showToast('+100 очков детектива')}function showToast(t){const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)}

