const cases=[
 {level:'LEVEL 1',file:'FILE No. 001',title:'The Missing Student',desc:'Открой замки архива, восстанови формы глаголов и найди ошибки в деле пропавшего студента.',action:'НАЧАТЬ РАССЛЕДОВАНИЕ',img:'assets/school.png',type:'verbcase'},
 {level:'LEVEL 2',file:'CASE No. 014',title:'The Evidence Room',desc:'Сопоставь улики, восстанови показание свидетеля и выстрой события в правильном порядке.',action:'ИЗУЧИТЬ УЛИКИ',img:'assets/evidence-room-room.png',type:'evidence'},
 {level:'LEVEL 3',file:'CASE No. 021',title:'Signal Intercept',desc:'Перехвати пять повреждённых сообщений и восстанови их точный английский текст.',action:'ПРИНЯТЬ СИГНАЛ',img:'assets/signal-intercept/case-021-cover.png',type:'signal'},
 {level:'LEVEL 4',file:'CASE No. ???',title:'Classified Case',desc:'Материалы дела засекречены. Доступ откроется позже.',action:'ДЕЛО ЗАКРЫТО',img:'assets/library-lock.png',type:'locked',locked:true}];
const grid=document.querySelector('#caseGrid'),modal=document.querySelector('#modal'),gameBody=document.querySelector('#gameBody');
grid.innerHTML=cases.map((c,i)=>{const done=c.type==='signal'?localStorage.getItem('signalInterceptComplete')==='yes':c.type==='evidence'&&localStorage.getItem('evidenceRoomComplete')==='yes';return `<article class="dossier ${done?'complete':''} ${c.locked?'locked':''}" ${c.locked?'aria-disabled="true"':`tabindex="0" data-open="${i}"`}><span class="tab">${c.level}</span><span class="file-no">${c.file}</span><div class="case-inner"><div class="photo"><img src="${c.img}" alt="Иллюстрация дела ${c.title}"></div><div class="case-copy"><h3>${c.title}</h3><p>${c.desc}</p></div></div><span class="mark">${c.locked?'ACCESS<br>DENIED':`CASE<br>${done?'COMPLETE':'ACTIVE'}`}</span><button class="open-case" ${c.locked?'disabled':''}>${c.locked?'ДОСТУП ЗАКРЫТ':done?'ПРОЙТИ ЕЩЁ РАЗ':c.action}</button></article>`}).join('');
const carousel=document.querySelector('.case-carousel');
document.querySelector('.case-arrow.prev').onclick=()=>grid.scrollBy({left:-grid.clientWidth*.82,behavior:'smooth'});
document.querySelector('.case-arrow.next').onclick=()=>grid.scrollBy({left:grid.clientWidth*.82,behavior:'smooth'});
let caseDrag=null,blockCaseClick=false;
grid.addEventListener('pointerdown',e=>{if(e.button!==0)return;caseDrag={x:e.clientX,left:grid.scrollLeft,moved:false,id:e.pointerId,card:e.target.closest('.dossier[data-open]'),launchButton:e.target.closest('.open-case')};grid.setPointerCapture(e.pointerId)});
grid.addEventListener('pointermove',e=>{if(!caseDrag||e.pointerId!==caseDrag.id)return;const distance=e.clientX-caseDrag.x;if(Math.abs(distance)>5){caseDrag.moved=true;grid.classList.add('dragging')}grid.scrollLeft=caseDrag.left-distance});
function finishCaseDrag(e){if(!caseDrag||e.pointerId!==caseDrag.id)return;const drag=caseDrag,mobile=matchMedia('(max-width:700px)').matches;blockCaseClick=true;caseDrag=null;grid.classList.remove('dragging');if(grid.hasPointerCapture(e.pointerId))grid.releasePointerCapture(e.pointerId);if(!drag.moved&&drag.card&&(!mobile||drag.launchButton))openGame(+drag.card.dataset.open);setTimeout(()=>{blockCaseClick=false},0)}
grid.addEventListener('pointerup',finishCaseDrag);grid.addEventListener('pointercancel',finishCaseDrag);
grid.addEventListener('click',e=>{if(blockCaseClick){e.preventDefault();e.stopPropagation()}},true);
window.addEventListener('evidence-room-complete',()=>{const card=grid.querySelector('.dossier[data-open="1"]');if(!card)return;card.classList.add('complete');card.querySelector('.mark').innerHTML='CASE<br>COMPLETE';card.querySelector('.open-case').textContent='ПРОЙТИ ЕЩЁ РАЗ'});
window.addEventListener('signal-intercept-complete',()=>{const card=grid.querySelector('.dossier[data-open="2"]');if(!card)return;card.classList.add('complete');card.querySelector('.mark').innerHTML='CASE<br>COMPLETE';card.querySelector('.open-case').childNodes[0].textContent='ПРОЙТИ ЕЩЁ РАЗ '});
const login=document.querySelector('.login'),nameModal=document.querySelector('#nameModal'),nameInput=document.querySelector('#detectiveName');
function escapeHtml(s){const x=document.createElement('span');x.textContent=s;return x.innerHTML}function avatarSrc(value=localStorage.getItem('detectiveAvatar')){return value==='male'?'assets/detective-avatar-male.png':'assets/detective-avatar.png'}function setDetective(name){if(name){login.classList.add('detective');login.title='Изменить имя или аватар';login.setAttribute('aria-label','Изменить имя или аватар');login.innerHTML=`<img src="${avatarSrc()}" alt=""><span>Детектив ${escapeHtml(name)}</span>`}}function openName(){nameModal.classList.add('active');nameInput.value=localStorage.getItem('detectiveName')||'';const avatar=localStorage.getItem('detectiveAvatar')||'female',choice=document.querySelector(`[name="detectiveAvatar"][value="${avatar}"]`);if(choice)choice.checked=true;setTimeout(()=>nameInput.focus(),30)}function closeName(){nameModal.classList.remove('active')}
setDetective(localStorage.getItem('detectiveName'));login.onclick=openName;document.querySelector('#nameForm').onsubmit=e=>{e.preventDefault();const n=nameInput.value.trim().replace(/\s+/g,' '),avatar=document.querySelector('[name="detectiveAvatar"]:checked')?.value||'female';if(n){localStorage.setItem('detectiveName',n);localStorage.setItem('detectiveAvatar',avatar);setDetective(n);closeName();showToast(`Добро пожаловать, детектив ${n}`)}};document.querySelectorAll('[data-name-close]').forEach(x=>x.onclick=closeName);
document.addEventListener('click',e=>{const scroll=e.target.closest('[data-scroll-cases]');if(scroll){document.querySelector('#cases')?.scrollIntoView({behavior:'smooth',block:'start'});return}const op=e.target.closest('[data-open]'),mobile=matchMedia('(max-width:700px)').matches;if(op&&(!mobile||e.target.closest('.open-case')))openGame(+op.dataset.open);if(e.target.closest('[data-close]'))closeGame(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(nameModal.classList.contains('active'))closeName();else if(modal.classList.contains('active'))closeGame(true)}if(e.key==='Enter'&&e.target.matches('.dossier'))openGame(+e.target.dataset.open)});
function openGame(i){const c=cases[i];const special=c.type==='evidence'||c.type==='signal'||c.type==='verbcase';document.querySelector('#gameLevel').textContent=special?'':`${c.file} / ${c.level}`;document.querySelector('#progress').textContent=special?'':'ДЕЛО ОТКРЫТО';gameBody.innerHTML=c.type==='find'?findGame(c):c.type==='cipher'?cipherGame(c):'';modal.classList.add('active');document.body.style.overflow='hidden';modal.querySelector('.game').classList.toggle('heist-modal',false);modal.querySelector('.game').classList.toggle('evidence-modal',c.type==='evidence');modal.querySelector('.game').classList.toggle('signal-modal',c.type==='signal');modal.querySelector('.game').classList.toggle('missing-modal',c.type==='verbcase');if(c.type==='evidence')EvidenceRoom.start(gameBody,()=>closeGame(false));else if(c.type==='signal')SignalIntercept.start(gameBody,()=>closeGame(false));else if(c.type==='verbcase')MissingStudent.start(gameBody,()=>closeGame(false));else bindSimple(c.type)}
function closeGame(ask){const missingActive=document.querySelector('.ms-layout')&&!document.querySelector('.ms-complete'),evidenceActive=document.querySelector('.er-stage');if((missingActive||evidenceActive)&&!confirm('Ты точно хочешь выйти, детектив? Весь прогресс текущего этапа будет потерян.'))return;if(!missingActive&&!evidenceActive&&ask&&document.querySelector('.signal-game:not(.signal-results)')&&!confirm('Закрыть дело? Текущий прогресс будет потерян.'))return;if(window.SignalIntercept)SignalIntercept.stop();modal.classList.remove('active');document.body.style.overflow='';gameBody.innerHTML=''}
function findGame(c){return `<h2>${c.title}</h2><p class="intro">Осмотри место исчезновения. Найди 3 активные точки.</p><div class="clue-scene" style="background-image:url('${c.img}')"><button class="clue" style="left:44%;top:77%" data-clue="notebook"></button><button class="clue" style="left:79%;top:39%" data-clue="locker"></button><button class="clue" style="left:17%;top:28%" data-clue="window"></button></div><div class="clue-list"><span class="chip">Найдено: <b id="found">0</b>/3</span></div><p class="feedback" id="feedback">Улики слегка пульсируют.</p>`}
function cipherGame(c){return `<h2>${c.title}</h2><p class="intro">Шифр: △ = TRUST, ○ = NO, □ = ONE. Как переводится «△ ○ □»?</p><div class="clue-scene" style="background-image:url('${c.img}')"></div><div class="choice-grid"><button data-answer="bad">Доверься всем</button><button data-answer="good">Не доверяй никому</button><button data-answer="bad">Никто не верит</button></div><p class="feedback" id="feedback">Выбери точный перевод.</p>`}
function bindSimple(type){if(type==='find'){let n=0;document.querySelectorAll('.clue').forEach(b=>b.onclick=()=>{if(!b.classList.contains('found')){b.classList.add('found');document.querySelector('#found').textContent=++n;if(n===3)win('Все улики найдены!')}})}if(type==='cipher')document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>b.dataset.answer==='good'?win('Послание расшифровано!'):document.querySelector('#feedback').textContent='Эта версия неверна.')}
function win(msg){document.querySelector('#feedback').textContent=msg;document.querySelector('#progress').textContent='ДЕЛО РАСКРЫТО ✓';showToast('+100 очков детектива')}function showToast(t){const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)}

