(function(){
 const verbs=[['be','was, were','been'],['begin','began','begun'],['break','broke','broken'],['bring','brought','brought'],['buy','bought','bought'],['come','came','come'],['do','did','done'],['drink','drank','drunk'],['drive','drove','driven'],['eat','ate','eaten'],['find','found','found'],['get','got','got'],['give','gave','given'],['go','went','gone'],['know','knew','known'],['leave','left','left'],['make','made','made'],['read','read','read'],['run','ran','run'],['see','saw','seen'],['sit','sat','sat'],['speak','spoke','spoken'],['take','took','taken'],['write','wrote','written'],['build','built','built'],['catch','caught','caught'],['choose','chose','chosen'],['feel','felt','felt'],['fly','flew','flown'],['forget','forgot','forgotten'],['grow','grew','grown'],['hear','heard','heard'],['hold','held','held'],['lose','lost','lost'],['meet','met','met'],['pay','paid','paid'],['send','sent','sent'],['sleep','slept','slept'],['stand','stood','stood'],['swim','swam','swum']];
 const past=[['She ____ the library at six.','LEAVE','left'],['Tom ____ a note near the door.','FIND','found'],['The guard ____ the student yesterday.','SEE','saw'],['Alex ____ his backpack upstairs.','TAKE','took'],['Someone ____ the window.','BREAK','broke'],['The witness ____ to the detective.','SPEAK','spoke'],['Mia ____ a map of the school.','DRAW','drew'],['The student ____ home alone.','GO','went'],['The detective ____ a message on the desk.','WRITE','wrote'],['A witness ____ the missing backpack.','BRING','brought'],['The alarm ____ at midnight.','RING','rang'],['The teacher ____ the old photograph.','KEEP','kept'],['Someone ____ the evidence under a chair.','HIDE','hid'],['The guard ____ a strange noise upstairs.','HEAR','heard'],['Mara ____ the locker key in the hall.','LOSE','lost'],['The student ____ through the side door.','RUN','ran'],['A camera ____ the empty corridor.','SHOW','showed'],['The suspect ____ the blue folder.','STEAL','stole'],['The detective ____ the torn letter.','READ','read'],['They ____ a clue behind the clock.','PUT','put'],['The witness ____ nervous during the interview.','FEEL','felt'],['The lights ____ out after six.','GO','went'],['The principal ____ the police immediately.','CALL','called'],['Mara ____ the final clue at noon.','GET','got']];
 const pastHints={LEAVE:'leave → left → left',FIND:'find → found → found',SEE:'see → saw → seen',TAKE:'take → took → taken',BREAK:'break → broke → broken',SPEAK:'speak → spoke → spoken',DRAW:'draw → drew → drawn',GO:'go → went → gone',WRITE:'write → wrote → written',BRING:'bring → brought → brought',RING:'ring → rang → rung',KEEP:'keep → kept → kept',HIDE:'hide → hid → hidden',HEAR:'hear → heard → heard',LOSE:'lose → lost → lost',RUN:'run → ran → run',SHOW:'show → showed → shown',STEAL:'steal → stole → stolen',READ:'read → read → read',PUT:'put → put → put',FEEL:'feel → felt → felt',CALL:'call → called → called',GET:'get → got → got'};
 const story=[['Detective','Detective'],['Mara','Mara'],['has','has'],['finded','found'],['a','a'],['strange','strange'],['note.','note.'],['The','The'],['missing','missing'],['student','student'],['has','has'],['writed','written'],['three','three'],['names','names'],['on','on'],['it.','it.'],['His','His'],['friend','friend'],['has','has'],['gave','given'],['the','the'],['police','police'],['a','a'],['key,','key,'],['but','but'],['nobody','nobody'],['has','has'],['saw','seen'],['the','the'],['locker','locker'],['open.','open.'],['A','A'],['teacher','teacher'],['has','has'],['took','taken'],['a','a'],['photo','photo'],['of','of'],['the','the'],['hallway.','hallway.'],['The','The'],['guard','guard'],['has','has'],['spoken','spoken'],['to','to'],['two','two'],['witnesses.','witnesses.'],['They','They'],['have','have'],['went','gone'],['home,','home,'],['but','but'],['one','one'],['of','of'],['them','them'],['has','has'],['keeped','kept'],['the','the'],['student’s','student’s'],['phone.','phone.'],['Mara','Mara'],['has','has'],['readed','read'],['every','every'],['message','message'],['and','and'],['has','has'],['begun','begun'],['to','to'],['understand','understand'],['the','the'],['case.','case.']];
 function makeStory(text,fixes){return text.split(' ').map(word=>[word,fixes[word]||word])}
 const stories=[story,
  makeStory('Inspector Reed has discoverd a muddy footprint beside the library. A camera has catched a student near the stairs, but the image has become blurred. The principal has wrote down the time, and a teacher has gave Reed a torn notebook. Nobody has knew why the alarm started. One witness has took the wrong corridor, while another has forgetted the room number. Reed has finally finded a silver key under the desk.',{'discoverd':'discovered','catched':'caught','wrote':'written','gave':'given','knew':'known','took':'taken','forgetted':'forgotten','finded':'found'}),
  makeStory('Detective Cole has came to the school before sunrise. Someone has broke the science-room lock and has stole a red folder. The caretaker has saw wet footprints by the window. Two students have spoke about a hidden passage, but neither has went inside it. Cole has chose to search the basement. He has already found a torch, and the principal has sent the floor plan. A witness has drank some water before the interview and has begun to remember a face.',{'came':'come','broke':'broken','stole':'stolen','saw':'seen','spoke':'spoken','went':'gone','chose':'chosen','drank':'drunk'}),
  makeStory('Agent Blake has took charge of the missing-student case. The school nurse has wrote a list of visitors, and the guard has bringed the entry log. Someone has teared one page from it. Blake has spoke to the student’s closest friend, who has gave him an old ticket. The ticket has layed inside a book for months. A camera has showed the student near the gym, but nobody has known where he went next. Blake has just begun a search of the roof.',{'took':'taken','wrote':'written','bringed':'brought','teared':'torn','spoke':'spoken','gave':'given','layed':'lain','showed':'shown'})
 ];
 let root,onClose,s,taskPool;
 const shuffle=a=>[...a].sort(()=>Math.random()-.5),esc=x=>{const e=document.createElement('span');e.textContent=x;return e.innerHTML};
 function start(el,close){root=el;onClose=close;s={view:'levels',level:0,done:0,score:0,task:0,wrong:0,corrected:new Set(),sound:true};render()}
 function render(){root.innerHTML=`<div class="ms-game ${s.view==='game'?`level-bg level-${s.level}`:''}">${s.view==='levels'?levels():s.view==='complete'?complete():game()}</div>`;bind()}
 function levels(){return `<header class="ms-head"><div><b>THE MISSING STUDENT</b><small>FILE No. 001</small></div><span>ГРАММАТИЧЕСКИЙ АРХИВ</span></header><main class="ms-levels"><p>ВЫБЕРИ УРОВЕНЬ ДОПУСКА</p><h2>Восстанови записи<br>пропавшего студента</h2><div>${levelCard(1,'THREE FORMS','Восстанови пропущенную форму неправильного глагола.')}${levelCard(2,'PAST SIMPLE','Собери нужную форму из деталей замка.')}${levelCard(3,'PRESENT PERFECT','Найди ошибки в материалах расследования.')}</div></main>`}
 function levelCard(n,title,text){const images=['','assets/missing-student/level-three-forms.png','assets/missing-student/level-past-simple.png','assets/missing-student/level-present-perfect.png'],done=localStorage.getItem(`missingStudentLevel${n}Complete`)==='yes';return `<button data-level="${n}" class="${done?'level-done':''}"><img src="${images[n]}" alt=""><i>0${n}</i><b>${title}</b><span>${text}</span>${done?'<strong class="level-check" aria-label="Уровень пройден">✓</strong>':''}</button>`}
 function game(){return `${head()}<main class="ms-layout"><aside><div class="ms-vault-title"><span>АРХИВНЫЕ ЗАМКИ</span></div><div class="lock-grid">${Array.from({length:8},(_,i)=>`<div class="padlock ${i<s.done?'open':''} ${i===s.done?'current':''}"><i></i><b>${String(i+1).padStart(2,'0')}</b></div>`).join('')}</div>${s.level===2?`<div class="case-tools level-two-hint"><button data-action="hint" class="${s.asideHint?'active':''}" aria-pressed="${!!s.asideHint}">ПОДСКАЗКА</button>${s.asideHint?`<p>${esc(s.asideHint)}</p>`:''}</div>`:s.level===3?`<div class="case-tools"><button data-action="hint" class="${s.asideHint?'active':''}" aria-pressed="${!!s.asideHint}">ПОДСКАЗКА</button><button data-action="show-errors" class="${s.showErrors?'active':''}" aria-pressed="${s.showErrors}">${s.showErrors?'СКРЫТЬ ОШИБКИ':'ПОКАЗАТЬ, ГДЕ ОШИБКИ'}</button>${s.asideHint?`<p>${esc(s.asideHint)}</p>`:''}</div>`:''}</aside><section class="ms-task">${s.level===1?levelOne():s.level===2?levelTwo():levelThree()}</section></main>`}
 function head(){const levelName=['','LEVEL 1 · THREE FORMS','LEVEL 2 · PAST SIMPLE','LEVEL 3 · PRESENT PERFECT'][s.level];return `<header class="ms-head"><div><b>THE MISSING STUDENT</b><small>FILE No. 001</small></div><span>${levelName}</span><div>SCORE <b>${s.score}</b><button data-action="levels">ДРУГОЙ УРОВЕНЬ</button></div></header>`}
 function levelOne(){const t=taskPool[s.task],missing=t.missing,blank=Array.from({length:t.answer.replace(/[^a-z]/gi,'').length},()=>'_').join(' ');return `<h2>Восстанови пропущенную форму</h2><div class="verb-forms">${t.forms.map((x,i)=>`<span class="${i===missing?'blank':''}">${i===missing?blank:esc(x)}</span>`).join('<i>→</i>')}</div><label>Введи недостающую форму<input id="msAnswer" autocomplete="off" spellcheck="false"></label><button class="ms-confirm" data-action="check">ОТКРЫТЬ ЗАМОК</button><details class="forms-hint"><summary>ПОДСКАЗКА</summary><p>${t.forms.map(esc).join(' → ')}</p></details><div class="ms-feedback"></div>`}
 function buildWord(t){const left={...(s.chosen||{})};return t.answer.split('').map(ch=>{if((left[ch]||0)>0){left[ch]--;return `<button data-remove-letter="${ch}" title="Убрать букву">${ch}</button>`}return '_'}).join('')}
 function levelTwo(){const t=taskPool[s.task],built=buildWord(t);return `<p class="letter-help">Нажимай буквы в любом порядке. Повторное нажатие убирает выбранную букву.</p><h2>${esc(t.sentence).replace('____',`<mark class="built-word">${built}</mark>`)}</h2><p class="base-verb">VERB · <b>${t.base}</b></p><div class="letter-lock">${t.tiles.map((x,i)=>`<button data-letter="${x}" data-tile="${i}" class="${s.used?.has(i)?'selected':''}">${x}</button>`).join('')}</div><button class="ms-confirm" data-action="check-letters">ПРОВЕРИТЬ СЛОВО</button><div class="ms-feedback"></div>`}
 function levelThree(){return `<h2>Протокол расследования</h2><article class="case-text">${s.story.map((w,i)=>s.corrected.has(i)?`<span>${esc(w[1])}</span>`:s.editing===i?`<span class="word-editor ${s.editError?'error':''}"><input id="wordCorrection" value="${esc(s.editValue??w[0])}" aria-label="Исправление слова ${esc(w[0])}"><button data-action="save-word" aria-label="Проверить">✓</button><button data-action="cancel-word" aria-label="Отмена">×</button>${s.editError?'<small>Форма неверна - попробуй ещё раз</small>':''}</span>`:`<button data-word="${i}" class="${s.showErrors&&w[0]!==w[1]?'revealed-error':''}">${esc(w[0])}</button>`).join(' ')}</article><p class="case-hint">В тексте спрятаны 8 ошибок. Нажми на подозрительное слово и исправь его.</p><div class="ms-feedback"></div>`}
 function bind(){root.onclick=click;const input=root.querySelector('#msAnswer');if(input){input.focus();input.onkeydown=e=>{if(e.key==='Enter')checkOne()}}const correction=root.querySelector('#wordCorrection');if(correction){correction.focus();correction.select();correction.oninput=e=>s.editValue=e.target.value;correction.onkeydown=e=>{if(e.key==='Enter')checkEditedWord();if(e.key==='Escape')cancelEdit()}}}
 function click(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.level){choose(+b.dataset.level);return}if(b.dataset.letter){pickLetter(b);return}if(b.dataset.removeLetter){removeLetter(b.dataset.removeLetter);return}if(b.dataset.word!==undefined){editWord(+b.dataset.word);return}const a=b.dataset.action;if(a==='check')checkOne();else if(a==='check-letters')checkLetters();else if(a==='save-word')checkEditedWord();else if(a==='cancel-word')cancelEdit();else if(a==='show-errors'){s.showErrors=!s.showErrors;render()}else if(a==='levels'){if(confirmExit()){s.view='levels';render()}}else if(a==='again'){s.view='levels';render()}else if(a==='close')onClose();else if(a==='hint'){s.asideHint=s.asideHint?'':s.level===2?pastHints[taskPool[s.task].base]:'Ищи ошибки именно в формах глаголов после has и have.';render()}}
 function confirmExit(){return confirm('Ты точно хочешь выйти, детектив? Весь прогресс текущего уровня будет потерян.')}
 function choose(level){s.level=level;s.done=0;s.score=0;s.task=0;s.corrected=new Set();s.used=new Set();s.chosen={};s.letters='';s.editing=null;s.editValue='';s.editError=false;s.showErrors=false;s.asideHint='';s.view='game';if(level===1)taskPool=shuffle(verbs).slice(0,8).map(v=>{const missing=Math.floor(Math.random()*3);return{forms:v,missing,answer:v[missing]}});if(level===2)taskPool=shuffle(past).slice(0,8).map(x=>{const answer=x[2],decoys=shuffle('abcdefghijklmnoprstuvwy'.split('')).slice(0,4),tiles=shuffle([...answer,...decoys]);return{sentence:x[0],base:x[1],answer,tiles}});if(level===3)s.story=shuffle(stories)[0];render()}
 function checkOne(){const input=root.querySelector('#msAnswer'),t=taskPool[s.task],clean=x=>x.trim().toLowerCase().replace(/\s*,\s*/g,',').replace(/\s+/g,' ');if(clean(input.value)===clean(t.answer)){unlock()}else{input.classList.add('wrong');feedback('Форма не подходит. Проверь ряд ещё раз.','bad')}}
 function pickLetter(b){const t=taskPool[s.task],tile=+b.dataset.tile,letter=b.dataset.letter.toLowerCase(),need=countLetters(t.answer);s.used=s.used||new Set();if(s.used.has(tile)){s.used.delete(tile);rebuildChosen(t);render();return}if((s.chosen?.[letter]||0)>=(need[letter]||0)){b.classList.add('wrong');feedback('Эта деталь не подходит или уже использована.','bad');return}s.used.add(tile);rebuildChosen(t);render()}
 function countLetters(word){const out={};for(const ch of word)out[ch]=(out[ch]||0)+1;return out}
 function rebuildChosen(t){s.chosen={};for(const i of s.used){const ch=t.tiles[i].toLowerCase();s.chosen[ch]=(s.chosen[ch]||0)+1}}
 function removeLetter(letter){const t=taskPool[s.task],tile=[...s.used].find(i=>t.tiles[i].toLowerCase()===letter);if(tile!==undefined)s.used.delete(tile);rebuildChosen(t);render()}
 function checkLetters(){const t=taskPool[s.task],need=countLetters(t.answer),ok=Object.keys(need).every(ch=>(s.chosen?.[ch]||0)===need[ch])&&s.used.size===t.answer.length;if(ok)unlock();else feedback('Слово ещё не собрано. Выбери все нужные буквы.','bad')}
 function editWord(i){s.editing=i;s.editValue=s.story[i][0];s.editError=false;render()}
 function cancelEdit(){s.editing=null;s.editValue='';s.editError=false;render()}
 function checkEditedWord(){const i=s.editing,w=s.story[i],value=(root.querySelector('#wordCorrection')?.value||'').trim(),clean=x=>x.toLowerCase().replace(/[.,]/g,'');if(clean(value)===clean(w[1])&&w[0]!==w[1]){s.corrected.add(i);s.editing=null;s.editValue='';s.editError=false;unlock(true)}else{s.editValue=value;s.editError=true;render()}}
 function unlock(textMode=false){s.done++;s.score+=100;s.chosen={};s.used=new Set();s.letters='';s.asideHint='';tone();render();const lock=root.querySelectorAll('.padlock.open')[s.done-1];lock?.classList.add('just-opened');if(s.done>=8){localStorage.setItem(`missingStudentLevel${s.level}Complete`,'yes');setTimeout(()=>{s.view='complete';render()},650)}else if(!textMode){s.task++;setTimeout(render,500)}}
 function feedback(text,kind){const f=root.querySelector('.ms-feedback');if(f){f.textContent=text;f.className='ms-feedback '+kind}}
 function tone(){if(!s.sound)return;try{const sound=new Audio('lock-in-interior-door.mp3');sound.volume=.65;sound.currentTime=0;sound.play().catch(()=>{})}catch(e){}}
 function complete(){const name=(localStorage.getItem('detectiveName')||'').trim(),detective=name?`детектив ${esc(name)}`:'детектив',praise=['','Браво','Блестяще выполнено','Превосходная работа'][s.level];return `<section class="ms-complete"><span>Уровень ${s.level} завершён · ${s.score} очков</span><div class="big-lock"><i></i>✓</div><p>ARCHIVE UNLOCKED</p><h2>${praise},<br>${detective}!</h2><div><button data-action="again">ВЫБРАТЬ ДРУГОЙ УРОВЕНЬ</button><button data-action="close">ВЕРНУТЬСЯ К ДЕЛАМ</button></div></section>`}
 window.MissingStudent={start};
})();




